#This class configure clamd

#parameter [clamd_options] NOT CHANGE, this parameter is usage for template
class clamav::clamd (

  $clamd_package = $clamav::clamd_package,
  $clamd_package_version = $clamav::clamd_package_version,
  $clamd_config = $clamav::clamd_config,
  $clamd_service = $clamav::clamd_service,
  $clamd_service_ensure = $clamav::clamd_service_ensure,
  $clamd_service_enable = $clamav::clamd_service_enable,
  $clamd_algorithmic_detection            =  true,
  $clamd_allow_all_match_scan               =  true,
  $clamd_allow_supplementary_groups        =  true,
  $clamd_archive_block_encrypted          =  false,
  $clamd_bytecode                        =  true,
  $clamd_bytecode_security                =  'TrustSigned',
  $clamd_bytecode_timeout                 =  '60000',
  $clamd_command_read_timeout              =  '5',
  $clamd_cross_filesystems               =  true,
  $clamd_database_directory               =  $clamav::clamd_databasedirectory,
  $clamd_debug                           =  false,
  $clamd_detect_broken_executables         =  false,
  $clamd_detect_pua                       =  false,
  $clamd_disable_cert_check                =  false,
  $clamd_exit_on_oom                       =  false,
  $clamd_extended_detection_info           =  true,
  $clamd_fix_stale_socket                  =  true,
  $clamd_follow_directory_symlinks         =  false,
  $clamd_follow_file_symlinks             =  false,
  $clamd_force_to_disk                     =  false,
  $clamd_foreground                      =  false,
  $clamd_heuristic_scan_precedence         =  false,
  $clamd_idle_timeout                     =  '31',
  $clamd_leave_temporary_files             =  false,
  $clamd_local_socket                    =  $clamav::clamd_localsocket,
  $clamd_local_socket_group               =  $clamav::clamd_group,
  $clamd_local_socket_mode                 =  '666',
  $clamd_log_clean                      =  false,
  $clamd_log_facility                     =  'LOG_LOCAL6',
  $clamd_log_file                         =  $clamav::clamd_logfile,
  $clamd_log_file_max_size                 =  '0',
  $clamd_log_fileunlock                   =  false,
  $clamd_log_rotate                       =  $clamav::clamd_logrotate,
  $clamd_log_syslog                      =  $clamav::clamd_logsyslog,
  $clamd_log_time                        =  true,
  $clamd_log_verbose                      =  false,
  $clamd_max_connection_queue_length        =  '15',
  $clamd_max_directory_recursion           =  '15',
  $clamd_max_embedded_pe                   =  '10M',
  $clamd_max_html_no_tags                   =  '2M',
  $clamd_max_html_normalize                =  '10M',
  $clamd_max_queue                        =  '101',
  $clamd_max_script_normalize              =  '5M',
  $clamd_max_threads                      =  '12',
  $clamd_max_zip_type_rcg                   =  '1M',
  $clamd_ole2_block_macros                 =  false,
  $clamd_official_database_only            =  false,
  $clamd_phishing_always_block_cloak        =  false,
  $clamd_phishing_always_block_ssl_mismatch  =  false,
  $clamd_phishing_scan_urls                =  true,
  $clamd_phishing_signatures              =  true,
  $clamd_pid_file                         =  $clamav::clamd_pidfile,
  $clamd_read_timeout                     =  '190',
  $clamd_scan_archive                     =  true,
  $clamd_scan_elf                         =  true,
  $clamd_scan_html                        =  true,
  $clamd_scan_mail                        =  true,
  $clamd_scan_ole2                        =  true,
  $clamd_scan_on_access                    =  false,
  $clamd_scan_pe                          =  true,
  $clamd_scan_partial_messages             =  false,
  $clamd_scan_swf                         =  true,
  $clamd_self_check                       =  '3600',
  $clamd_send_buf_timeout                  =  '200',
  $clamd_stream_max_length                 =  '25M',
  $clamd_structured_data_detection         =  false,
  $clamd_temporary_directory              =  $clamav::clamd_temporarydirectory,
  $clamd_user                            =  $clamav::clamd_user,

  Hash $clamd_options = {
    'AlgorithmicDetection'           => $clamd_algorithmic_detection,
    'AllowAllMatchScan'              => $clamd_allow_all_match_scan,
    'AllowSupplementaryGroups'       => $clamd_allow_supplementary_groups,
    'ArchiveBlockEncrypted'          => $clamd_archive_block_encrypted,
    'Bytecode'                       => $clamd_bytecode,
    'BytecodeSecurity'               => $clamd_bytecode_security,
    'BytecodeTimeout'                => $clamd_bytecode_timeout,
    'CommandReadTimeout'             => $clamd_command_read_timeout,
    'CrossFilesystems'               => $clamd_cross_filesystems,
    'DatabaseDirectory'              => $clamav::clamd_databasedirectory,
    'Debug'                          => $clamd_debug,
    'DetectBrokenExecutables'        => $clamd_detect_broken_executables,
    'DetectPUA'                      => $clamd_detect_pua,
    'DisableCertCheck'               => $clamd_disable_cert_check,
    'ExitOnOOM'                      => $clamd_exit_on_oom,
    'ExtendedDetectionInfo'          => $clamd_extended_detection_info,
    'FixStaleSocket'                 => $clamd_fix_stale_socket,
    'FollowDirectorySymlinks'        => $clamd_follow_directory_symlinks,
    'FollowFileSymlinks'             => $clamd_follow_file_symlinks,
    'ForceToDisk'                    => $clamd_force_to_disk,
    'Foreground'                     => $clamd_foreground,
    'HeuristicScanPrecedence'        => $clamd_heuristic_scan_precedence,
    'IdleTimeout'                    => $clamd_idle_timeout,
    'LeaveTemporaryFiles'            => $clamd_leave_temporary_files,
    'LocalSocket'                    => $clamav::clamd_localsocket,
    'LocalSocketGroup'               => $clamav::clamd_group,
    'LocalSocketMode'                => $clamd_local_socket_mode,
    'LogClean'                       => $clamd_log_clean,
    'LogFacility'                    => $clamd_log_facility,
    'LogFile'                        => $clamd_log_file,
    'LogFileMaxSize'                 => $clamd_log_file_max_size,
    'LogFileUnlock'                  => $clamd_log_fileunlock,
    'LogRotate'                      => $clamav::clamd_logrotate,
    'LogSyslog'                      => $clamav::clamd_logsyslog,
    'LogTime'                        => $clamd_log_time,
    'LogVerbose'                     => $clamd_log_verbose,
    'MaxConnectionQueueLength'       => $clamd_max_connection_queue_length,
    'MaxDirectoryRecursion'          => $clamd_max_directory_recursion,
    'MaxEmbeddedPE'                  => $clamd_max_embedded_pe,
    'MaxHTMLNoTags'                  => $clamd_max_html_no_tags,
    'MaxHTMLNormalize'               => $clamd_max_html_normalize,
    'MaxQueue'                       => $clamd_max_queue,
    'MaxScriptNormalize'             => $clamd_max_script_normalize,
    'MaxThreads'                     => $clamd_max_threads,
    'MaxZipTypeRcg'                  => $clamd_max_zip_type_rcg,
    'OLE2BlockMacros'                => $clamd_ole2_block_macros,
    'OfficialDatabaseOnly'           => $clamd_official_database_only,
    'PhishingAlwaysBlockCloak'       => $clamd_phishing_always_block_cloak,
    'PhishingAlwaysBlockSSLMismatch' => $clamd_phishing_always_block_ssl_mismatch,
    'PhishingScanURLs'               => $clamd_phishing_scan_urls,
    'PhishingSignatures'             => $clamd_phishing_signatures,
    'PidFile'                        => $clamav::clamd_pidfile,
    'ReadTimeout'                    => $clamd_read_timeout,
    'ScanArchive'                    => $clamd_scan_archive,
    'ScanELF'                        => $clamd_scan_elf,
    'ScanHTML'                       => $clamd_scan_html,
    'ScanMail'                       => $clamd_scan_mail,
    'ScanOLE2'                       => $clamd_scan_ole2,
    'ScanOnAccess'                   => $clamd_scan_on_access,
    'ScanPE'                         => $clamd_scan_pe,
    'ScanPartialMessages'            => $clamd_scan_partial_messages,
    'ScanSWF'                        => $clamd_scan_swf,
    'SelfCheck'                      => $clamd_self_check,
    'SendBufTimeout'                 => $clamd_send_buf_timeout,
    'StreamMaxLength'                => $clamd_stream_max_length,
    'StructuredDataDetection'        => $clamd_structured_data_detection,
    'TemporaryDirectory'             => $clamav::clamd_temporarydirectory,
    'User'                           => $clamav::clamd_user,
  },
){

  #install clamd
  package { $clamd_package:
    ensure => $clamd_package_version,
  }

   file { 'clamd_file':
    ensure  => file,
    name    => $clamd_config,
    mode    => '0644',
    content => epp('clamav/clamd.conf'),
  }

  service { 'clamd_service':
    ensure     => $clamd_service_ensure,
    name       => $clamd_service,
    enable     => $clamd_service_enable,
    hasrestart => true,
    hasstatus  => true,
    subscribe  => [Package[$clamd_package], File['clamd_file']],
  }

  Package[$clamd_package] -> File['clamd_file'] ~> Service['clamd_service']

}
